### ISSUE TITLE
pod broker fails to template xfce-desktop

### ISSUE THREAD

**Issue by russelleason** [selkies-project/selkies-vdi#2]
kubectl -n pod-broker-system logs -f pod-broker-0 -c pod-broker

```error templating file: /var/run/buildsrc/apps/xfce-desktop/jsonpatch-service-selectors.yaml.tmpl: template: jsonpatch-service-selectors.yaml.tmpl:15:18: executing "jsonpatch-service-selectors.yaml.tmpl" at <.AppSpec.Type>: can't evaluate field Type in type pod_broker.AppConfigSpec```

**Comment by danisla** [comment]
@russelleason, the error <.AppSpec.Type>: can't evaluate sounds like an issue with the pod-broker not being updated per changes on the master branch...

My suggestion is to do the following from the master branch in the [selkies-project/selkies repo](https://github.com/selkies-project/selkies.git):

1. from the `setup/` directory. run cloud build to update the installer image.
2. from the `images/` directory, run cloud build to update the broker images.
3. from the `setup/manifests` directory, run cloud build to deploy the new broker image.

**Comment by russelleason** [comment]
Hey, I was able to get past this error with your updated steps, thanks!
