### ISSUE TITLE
X server no longer loads on latest version of COS 85.13310.1041.24

### ISSUE THREAD

**Issue by jkwong888** [selkies-project/selkies-vdi#4]
The latest version of COS (85.13310.1041.24) has updated the fixed driver installer image `cos-driver-installer:fixed` to use a binary instead of a bash script for driver installation.  Also it looks like the location it installs the drivers has changed, which leads to xserver not starting anymore:

```
[  1372.688] (**) ModulePath set to "/usr/local/nvidia/lib64,/usr/lib/xorg/modules"
...
[  1372.708] (II) LoadModule: "nvidia"
[  1372.709] (WW) Warning, couldn't open module nvidia
```

we hacked around this using the original cos-config configmap and forcing the driver installer to run the custom entrypoint script, and merging some of the volumes and paths from the upstream installer daemonset: https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml

at some point, should selkies use the same install method as upstream?

**Comment by jkwong888** [comment]
btw just to correct myself above, the default installer in the `cos-driver-installer:fixed` doesn't seem to build the xserver modules anymore or create `/usr/local/nvidia/lib64/xorg`.  but when we run it through the custom entrypoint, it does.

**Comment by danisla** [comment]
The COS driver installer image changed. Fixed in this commit: https://github.com/selkies-project/selkies-vdi/commit/015ee1a004efba83540dc35c4b2dd4f704af5d55
